GEMINI_API_KEY = "AIzaSyBcz0T1Q27lm3T855CrkqECNzE5WgiBzPU"
````

2. Streamlitアプリ内でAPIキーを取得するには、以下のようにします。

````python
# filepath: [app.py](http://_vscodecontentref_/0)

import streamlit as st

api_key = st.secrets["GEMINI_API_KEY"]

st.write("Gemini APIキー:", api_key)